import hmac
import hashlib
import os
from urllib.parse import urlparse, urlunparse
from tenacity import retry, wait_exponential_jitter, stop_after_attempt
from .config import settings

_IN_DOCKER = os.path.exists("/.dockerenv")


def resolve_callback_url(url: str) -> str:
    """Rewrite localhost URLs to host.docker.internal when running in Docker."""
    if not _IN_DOCKER:
        return url
    parsed = urlparse(url)
    if parsed.hostname in ("localhost", "127.0.0.1"):
        parsed = parsed._replace(
            netloc=parsed.netloc.replace(parsed.hostname, "host.docker.internal")
        )
        return urlunparse(parsed)
    return url


def ulid(prefix: str = "p") -> str:
    """
    Legacy ULID function - now returns a placeholder.
    The actual ID will be generated by the database auto-increment.
    This function is kept for API compatibility but not used for ID generation.
    """
    return "temp"  # Temporary placeholder, real ID comes from DB


def sign_body(body: bytes) -> str:
    sig = hmac.new(
        settings.CALLBACK_SIGNING_SECRET.get_secret_value().encode(), body, hashlib.sha256
    ).hexdigest()
    return f"sha256={sig}"


@retry(wait=wait_exponential_jitter(initial=0.5, max=8), stop=stop_after_attempt(5))
async def retryable_http_post(client, url: str, body: bytes, headers: dict):
    resp = await client.post(url, content=body, headers=headers)
    resp.raise_for_status()
    return resp
