name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: write
      packages: write
    uses: NexteraLabs/common_pipelines/.github/workflows/build_push.yml@main
    with:
      image_name: telegram-prompt-api
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
